name: Create and deploy DACPAC

on: 
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  build:
    name: Build DACPAC
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
